* Dropbox Utilities
Wraps around dropbox API and provides functionality for reading and writing 
various types of files

** Readers
All readers follow the following algorithm: 
- Convert dropbox path into a link. A maximum number of attempts 
  are made to generate the link. After those fail, an exception is raised
- Read the link into a in-memory buffer, a BytesIO instance
- Use your custom reader, to read from bytes io instance
The current set readers provide functionality for reading the following types of
files: 
- CSV files into pandas dataframes
- Excel files into pandas dataframes
- Config/INI files into Configparser instance

** Writers
All writers follow the following algorithm
- Write the data to buffer this could be either StringIO or bytesIO
- Convert this buffer to bytes. In case of string, encode it with propery encoding ('UTF-8')
- Use the dropbox library to upload to the appropriate location
- The current set of writers provide functionality for writing the following types of files:
- Dataframes to csv files
- Dataframes to excel files

** Logger

Logger writes bytes data to a path on dropbox

[TBC]



List file metadata in a folder. The function provides functionality 
with the following parameters : 
Arrange by : the order in which the files are retrieved
recursive: List files recursively or not
hidden: List hidden files or not











Books: 

SICP : Structure and interpretation of computer programs


Clean Code: Bob martin


Pragmatic programmer


Programming : 

Low level: 

1) C++ 

2) Rust


Functional Programming : 

Scheme 

Clojure

Haskell *


OOP :

1) Smalltalk

2) Java


Multiparadigm 


1) Python

2) Javascript

3) GO


